services:
  node:
    image: alphaticks/starknet-node:1.0
    ports: 
      - "9545:9545"
    environment:
      - ETHEREUM_URL=<your-url-to-node-provider>
    volumes:
      - type: volume
        source: pathfinder_data
        target: /usr/share/pathfinder/data

volumes:
  pathfinder_data:
